name: Counter
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Count
        run: |
          echo "Counting..."
          count=$(cat count.txt)
          echo "Current count is $count"
          count=$((count + 1))
          echo "New count is $count"
          echo $count > count.txt
      - name: Commit and push
        run: |
          git config --global user.name 'marlin0'
          git config --global user.email 'marlinmail@qq.com'
          git add count.txt
          git commit -m "Update count"
          git push
